### ISSUE TITLE
Strange code in main.css

### ISSUE THREAD

**Issue by lynn9388** [LeNPaul/Lagrange#29]
I don't have much knowledge about css, so I am not sure if the code in the 270th line is correct. I have checked the code in VS code and WebStorm, they all show **'}' expected**. 

```css
pre {
    padding: 8px 12px;
    overflow-x: auto;

    > code {
        border: 0;
        padding-right: 0;
        padding-left: 0;
    }
}
```

**Comment by alesmit** [comment]
Hi @lynn9388 !

that is SCSS code. basically it's the same thing as writing it like this:
```scss
pre {
    padding: 8px 12px;
    overflow-x: auto;
}

pre > code {
  border: 0;
  padding-right: 0;
  padding-left: 0;
}
```

the `>` targets the `code` direct child of a `pre` tag.
