### ISSUE TITLE
Why the contents in this file isn't changed that i edit

### ISSUE THREAD

**Issue by syh4661** [LeNPaul/Lagrange#60]
Why the contents in this file isn't changed that i edit

It is Lagrange title and github address in my repository

**Comment by syh4661** [comment]
There is a error in _config.yml file line number 15 the "paginate: 5" part in github page

**Comment by ghost** [comment]
Could you please post the contents of your `_config.yml`?

**Comment by syh4661** [comment]
Here is my code
```
# Site Build Settings
# Jekyll-paginate-v2 configuration
pagination:
 enabled: true
 per_page: 5
 permalink: '/page/:num/'
 title: ':title - page :num of :max'
 limit: 0
 sort_field: 'date'
 sort_reverse: true

# jekyll-paginate configuration

paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]


# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: 'Hyeok'
description: 'Hyeok's homepage'
author: 'SYH'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

theme: jekyll-theme-midnight

```
